name: opencv install and build
description: caches a cmake installation of opencv; intended for gocv static builds
inputs:
  version:
    description: gocv version from which to pull build script
    default: v0.41.0
  static:
    default: ''
runs:
  using: composite
  steps:
  - id: cache
    uses: actions/cache@v4
    with:
      path: c:/opencv
      # second field in cache key is gocv version from which we copied the build steps
      # todo: add runner.version maybe or at least something which tracks different win versions
      key: ${{ runner.os }}-${{ inputs.version }}-${{ inputs.static }}
  - if: steps.cache.outputs.cache-hit != 'true'
    run: |
      curl --fail --location https://raw.githubusercontent.com/hybridgroup/gocv/refs/tags/${{ inputs.version }}/win_build_opencv.cmd --output win_build_opencv.cmd
      # we remove the final `chdir` because it's 1) wrong on systems that have go and 2) extra-wrong here
      head -n -1 win_build_opencv.cmd > build.cmd
    shell: bash
  - if: steps.cache.outputs.cache-hit != 'true'
    shell: cmd
    run: build.cmd ${{ inputs.static }}
