name: opencv install and build
description: caches a cmake installation of opencv; intended for gocv static builds
inputs:
  version:
    description: the version of gocv (*not* of opencv) to use
    default: 'v0.41.0'
runs:
  using: composite
  steps:
  - run: curl https://raw.githubusercontent.com/hybridgroup/gocv/refs/tags/${{ inputs.version }}/win_build_opencv.cmd -o win_build_opencv.cmd
    shell: bash
  - id: cache
    uses: actions/cache@v4
    with:
      path: /opencv
      key: ${{ runner.os }}-${{ inputs.version }}
  - run: win_build_opencv.cmd
    shell: cmd
    if: steps.cache.outputs.cache-hit != 'true'
