name: opencv install and build
description: caches a cmake installation of opencv; intended for gocv static builds
runs:
  using: composite
  steps:
  - id: cache
    uses: actions/cache@v4
    with:
      path: c:/opencv
      # second field in cache key is gocv version from which we copied the build steps
      key: ${{ runner.os }}-v0.41.0
  - if: steps.cache.outputs.cache-hit != 'true'
    run: |
      wget https://raw.githubusercontent.com/viam-labs/win-cv-action/refs/tags/v0.41.0/win_build_opencv.cmd
      # we remove the final `chdir` because it's 1) wrong on systems that have go and 2) extra-wrong here
      head -n -1 win_build_opencv.cmd > build.cmd
    shell: bash
  - if: steps.cache.outputs.cache-hit != 'true'
    shell: cmd
    run: build.cmd static
