on:
  workflow_dispatch:

jobs:
  test:
    runs-on: windows-2025
    steps:
    - uses: viam-labs/win-cv-action@main
      with:
        static: static
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version-file: go.mod
    - name: build
      run: echo skip build # go build -tags opencvstatic .
